name: Publish Package to npm
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@softprobe'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm run build
        
      - name: Publish to npm
        uses: pnpm/action-publish@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 